### PR TITLE
Federated plugin refactor

### LINKED ISSUE #33: when forcing logout from init, in case of errors the plugin content is blank
from the plugin:

```
  /// Init SDK using apiKey and apiDomain
  Future<Map<String, dynamic>?> initSdk(String apiKey, String apiDomain,
      [bool forceLogout = true]) async {
    if (forceLogout) {
      await logout();
    }
```

sometimes, when there's some issue with the method logout:

```
 await _channel.invokeMethod(Methods.logOut.name).catchError((error) {
      debugPrint('Error logging out');
    }).timeout(getTimeout(Methods.logOut), onTimeout: () {
      debugPrint('A timeout that was defined in the request is reached');
      return timeoutError();
    });
```

the message "Error logging out" is shown on the console, and the login page inside the plugin is blank, no actions can be taken. Any way to handle the error and ignore the force logout?

Screenshot 2022-11-17 at 10 03 56

### LINKED ISSUE #35: The plugin's public API needs documentation & typing improvements
The current public API of the plugin, as viewed under the `LIBRARIES` section on pub.dev is rather hard to understand.

I note the following:
- methods that return a `Future<Map<String, dynamic>>` never document what exactly is in the returned Map.
   - I also wonder if the return type of those methods can be changed to a specific model class to make the typing more resilient
- the method `showScreenSet()` returns dynamic, which does not make sense. Is it void/Future<void>/something else?
- when passing a `Map<String, dynamic>` as arguments to a function, the function never documents what should be in the Map
- don't use `dynamic` for the type of a method parameter
- if a method has some Dartdoc documentation, it is _very short_ and does not really explain what the method does.
  Consider writing a paragraph of documentation that clearly explains the purpose of the method
  
I am aware that the plugin is in its early stages, I just wanted to highlight some things I noticed.
I am not sure if pull requests are welcome, I would certainly help out with cleaning this up a little.

### LINKED ISSUE #37: [Android] Crash when canceled `showScreenSet()`
On Android devices, when back from Web Screen-Set with hardware back key, `EventChannel('screensetEvents')` throws the following error (uncatchable) and the application crashes.

```
PlatformException(200001, Operation canceled, null, null)
```

The cause of this is the flutter side implementation of the plugin do not pass `onError` to `EventChannel('screensetEvents').receiveBroadcastStream().listen()`.

```
    const EventChannel _stream = EventChannel('screensetEvents');
    _screenSetsEventStream = _stream.receiveBroadcastStream().listen((onData) {
      onScreenSetEvent(
        onData['event'],
        onData['data'],
      );
      if (onData['event'] == 'onHide' || onData['event'] == 'onCanceled') {
        _screenSetsEventStream = null;
      }
    });
```

But, I think, Android's `onCanceled` should be returned  by `success()` instead of `error()` like `onError` in the first place.

Not really good:
```
            override fun onCanceled() {
                screenSetsEventsSink?.error("200001", "Operation canceled", null)
                screenSetsEventsHandler = null
                screenSetEventsChannel = null
                screenSetsEventsSink = null
            }
```

LGTM:
```
            override fun onCanceled() {
                screenSetsEventsSink?.success(
                    mapOf(
                        "event" to "onCanceled",
                        "data" to mapOf<String, Any>()
                    )
                )
                screenSetsEventsHandler = null
                screenSetEventsChannel = null
                screenSetsEventsSink = null
            }
```

Thank you.

### LINKED ISSUE #39: SessionInfo.expirationTime access on android crashing, since parsing logic is not handled for android
SessionInfo.expirationTime access on android crashing, since parsing logic is not handled for android

Removing the Platform.isIOS check will solve the issue

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR
- reimplements the Gigya Flutter plugin using the `plugin_platform_interface` package
- cleans up the public API by improving the documentation and specifying types where they were missing
- fixes the creation of the `ScreenSets` event channel, the event channel was not reused while it should have been
- fixes the Dart usage of the `ScreenSets` API. This now returns well-typed events and users can now cancel the `StreamSubscription` that is returned to them
- fixes an inconsistency between Android & iOS for the session expiration timestamp
- adds an analysis_options.yaml and fixes violations
- fixes various smaller bugs on the native side 

I also made a whole bunch of other changes, I'd refer to the changelog entry for that.

This PR is a big step towards adding web support to the plugin as well.
This would boil down to
1) adding a `web` entry in the pubspec.yaml which points to the implementation
2) implementing the platform interface using `static interop` with [package:js](https://pub.dev/packages/js)

While testing the example app, I had a few open questions:
- The `socialLogin()` method does not have a specific error code for when the permission dialog is canceled.
- The `OTP`, `SSO`, `Forgot Password` and `Login with passkey` routes return `GigyaError`s with no details at all
- I did not test the logged-in routes + the register route, as that might be easier to test internally

@tal-mi In regards to the readme changes, perhaps you could author a commit that updates the README?
I reverted those changes in https://github.com/SAP/gigya-flutter-plugin/pull/41/commits/677a3d31c1e25d624c29692d43dfcce91fdc6856 if you want to use pieces of the original change I made.

Fixes #33 
Fixes #35 
Fixes #37
Fixes #39

### CODE REVIEW

**Comment by navaronbracke** [comment]
@tal-mi You can start a preliminary review if you want. I still have to fixup the README and sample app (on the Dart side)
but that's about it.

**Comment by navaronbracke** [comment]
I had a few build errors for both Android and iOS, which I have addressed in the meantime.
I've also switched the Android build over to using the predefined debug keystore that Flutter provides.
There is no need to use a separate keystore file for the example app anyway.

Next, I'll take a look at some warnings for iOS (relating to bumping the min version to iOS 13.0)

Once those are fixed, the work on the native side is done and I'll start cleaning up the example app and the readme.

**Comment by tal-mi** [comment]
Hi,
Thank you for your contribution.
We will go over the changes in the upcoming week and verify.
Please refrain from changes in README & LICENCE because they cannot be approved and are subject to company regulations.

**Comment by navaronbracke** [comment]
@tal-mi Ok, I _did_ make a few changes there:
1) Apparently the Apache 2.0 license was included twice. I think that including it at the root of the project should be sufficient. (you might want to double check that with your legal team, maybe some of the code does not fall under the same license)
2) The README had a few typo's and was also getting quite large. I decided to fix the typo's / broken links.
3) Since the public API has been refactored, the usage detailed in the README is not always correct anymore.
     Should we instead redirect people to the example app?
     
I can send the new README over for review if you want?
I'll revert the changes to the LICENSE & README before marking this PR ready for review.

**Comment by navaronbracke** [comment]
I'm currently reworking the example app to work with the new API's. I'll try to finish that by the end of this week. Once that is finished, this PR should be ready for review.

**Comment by tal-mi** [comment]
Hi.
Please note that this review might take a while. All significant changes (especially breaking ones) must be approved by our product owner via an internal process.

**Comment by navaronbracke** [comment]
That's fine. If people really want to use this patch in the meantime (while it is still under review) they _can_ use a dependency override, i.e. https://dart.dev/tools/pub/dependencies#git-packages

**Comment by navaronbracke** [comment]
@tal-mi Do you have an update on the timeline to get this reviewed? Just following it up a little.

**Comment by tal-mi** [comment]
HI,
This PR is massive and needs a lot of coordination with the product to approve changes.
We will still release another plugin version without these changes for issues we already have in our backlog and then be free to overview this in detail.
I don't have a timeline yet but working on prioritizing it.

**Comment by navaronbracke** [comment]
Good to hear. I'll follow up when the new version is released so that we can keep these changes in sync.

**Comment by tal-mi** [comment]
Hi,
Just to update,
We will be releasing an intermediate version next week with updates to the core SDKS only. 
Your changes have been approved by PR and we will start running internal testing phases next week.
Expecting to release v1.0.0 with all changes provided.

Cheers,
Tal

**Comment by navaronbracke** [comment]
@tal-mi I am following up a little, and I noticed that the CHANGELOG.md now incorrectly lists version `0.1.4` twice,
each with a different changelog description. 

https://github.com/SAP/gigya-flutter-plugin/blob/main/CHANGELOG.md#014
https://github.com/SAP/gigya-flutter-plugin/blob/main/CHANGELOG.md#014-1

**Comment by mcg95** [comment]
This PR fails when trying to build for iOS due an issue in GigyaSdkExtensions.swift. 
`Error - Swift Compiler Error (Xcode): 'UIWindowScene' is only available in iOS 13.0 or newer`

Adding if #available fixes the issue.

image

**Comment by navaronbracke** [comment]
@mcg95 The minimum version of the plugin is now iOS 13.0, as mentioned in the changelog.

**Comment by mcg95** [comment]
@tal-mi Is there a timeline for the 1.0.0 release along with this PR? This PR seems to fix the issue I have posted last week.

Issue - https://github.com/SAP/gigya-flutter-plugin/issues/43

**Comment by tal-mi** [comment]
1.0.0 is currently in testing along with this PR. It will be released only after the Android v7 core update that contains changes to social login interfacing.
**Android v7 will be released today.

**Pull request merged**
