### PR TITLE
Fix forgotPassword crash on Android

### PR DESCRIPTION
**Pull request by galunecandrey**

### CODE REVIEW

**Comment by galunecandrey** [comment]
@tal-mi Can you check my MR?

**Comment by galunecandrey** [comment]
@tal-mi  When will you publish new package with this fix?

**Comment by tal-mi** [comment]
Sunday

**Comment by tal-mi** [comment]
We are evaluating an issue with the core iOS SDK.
New release will be available on 4th of October the latest.

**Pull request merged**
